### ISSUE TITLE
Public versioning and releases

### ISSUE THREAD

**Issue by hlmartin** [nib-health-funds/hammertime#3]
The README.md currently has a broken link (probably need to fix this!) to check the tags on this project for the latest release. We don't currently tag anything. We probably should have a releases page with versions, at the very least.

**Comment by ramesius** [comment]
We should probably put up a draft release to begin tagging things properly.

**Comment by krutisfood** [comment]
Setup initial release https://github.com/nib-health-funds/hammertime/releases/tag/v1.0.0
